@URL = http://localhost:3000/api
@TOKEN1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IuusuOykgOyLnTMiLCJ1c2VySWQiOjQsImVtYWlsIjoidGVzdDRAdGVzdDQudGVzdCIsImlhdCI6MTcwMTk0MzIxNiwiZXhwIjoxNzAxOTg2NDE2fQ.nnFAtzvCMMNrSP4EB04jRP4GgKQlym5kH0Tsd53PWtg
@TOKEN2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Iu2FjOyKpO2KuCIsInVzZXJJZCI6NiwiZW1haWwiOiJ0ZXN0NUB0ZXN0NS50ZXN0IiwiaWF0IjoxNzAxOTQzNjMzLCJleHAiOjE3MDE5ODY4MzN9.llnvXZ1P_LwuMRLHc1l5FQUD-oO8ebU-sreFLXq5eZ0

# 페이지 접속
GET http://localhost:3000/

###

# 회원가입
POST {{URL}}/signup
Content-Type: application/json

  {
    "email": "test4@test4.test",
    "userName": "문준식3",
    "password": "131313",
    "confirmPassword": "131313"
  }

###

# 로그인
POST {{URL}}/signin
Content-Type: application/json

  {
    "email": "test4@test4.test",
    "password": "131313"
  }

### 

# 사용자 조회 
GET {{URL}}/users/userInfo
Authorization: Bearer {{TOKEN1}}
